### ISSUE TITLE
Using the wrapper on MiniHack environment

### ISSUE THREAD

**Issue by saharad1** [ngoodger/nle-language-wrapper#3]
Hi,
I tried using the nle-language-wrapper with MiniHack environments but apparently, there is a problem that the environment observation keys are not aligned with the wrapper.
If I understand correctly the environments should have the following observation keys ["glyphs", "blstats", "tty_chars", "inv_letters", "inv_strs", "tty_cursor"] but the "tty_chars" and "tty_cursor" are not in any of the MiniHack environments (and sometimes there are more observation keys that are missing).
When trying to use it on MiniHack environment I get the following errors(The error is just the text after the 'Reason'):

Couldn't instantiate MiniHack-Room-Random-5x5-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Room-Dark-5x5-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Room-Monster-5x5-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Room-Trap-5x5-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Room-Ultimate-5x5-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Room-15x15-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Room-Random-15x15-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Room-Dark-15x15-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Room-Monster-15x15-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Room-Trap-15x15-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Room-Ultimate-15x15-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Corridor-R2-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Corridor-R3-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Corridor-R5-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-KeyRoom-Fixed-S5-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-KeyRoom-S5-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-KeyRoom-S15-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-KeyRoom-Dark-S5-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-KeyRoom-Dark-S15-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MazeWalk-9x9-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MazeWalk-Mapped-9x9-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MazeWalk-15x15-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MazeWalk-Mapped-15x15-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MazeWalk-45x19-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MazeWalk-Mapped-45x19-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-CorridorBattle-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-CorridorBattle-Dark-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N2-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N4-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N6-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N2-Locked-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N4-Locked-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N6-Locked-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N2-Lava-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N4-Lava-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N6-Lava-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N2-Monster-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N4-Monster-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N6-Monster-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N2-Extreme-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N4-Extreme-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-MultiRoom-N6-Extreme-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-LavaCrossingS9N1-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-LavaCrossingS9N2-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-LavaCrossingS9N3-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-LavaCrossingS11N5-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-SimpleCrossingS9N1-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-SimpleCrossingS9N2-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-SimpleCrossingS9N3-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-SimpleCrossingS11N5-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Memento-Short-F2-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Memento-F2-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Memento-F4-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Boxoban-Unfiltered-v0. Reason: To use Boxoban environments, please download maps using the minihack/scripts/download_boxoban_levels.py script.
Couldn't instantiate MiniHack-Boxoban-Medium-v0. Reason: To use Boxoban environments, please download maps using the minihack/scripts/download_boxoban_levels.py script.
Couldn't instantiate MiniHack-Boxoban-Hard-v0. Reason: To use Boxoban environments, please download maps using the minihack/scripts/download_boxoban_levels.py script.
Couldn't instantiate MiniHack-River-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-River-Monster-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-River-Lava-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-River-MonsterLava-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-River-Narrow-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-HideNSeek-Mapped-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-HideNSeek-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-HideNSeek-Lava-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-HideNSeek-Big-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Labyrinth-Big-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Labyrinth-Small-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-ExploreMaze-Easy-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-ExploreMaze-Hard-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-ExploreMaze-Easy-Mapped-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-ExploreMaze-Hard-Mapped-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'inv_letters', 'inv_strs', 'tty_chars'}
Couldn't instantiate MiniHack-Eat-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Pray-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Sink-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Wield-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Wear-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-PutOn-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Zap-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Read-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Eat-Fixed-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Pray-Fixed-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Sink-Fixed-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Wield-Fixed-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Wear-Fixed-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-PutOn-Fixed-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Zap-Fixed-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Read-Fixed-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Eat-Distr-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Pray-Distr-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Sink-Distr-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Wield-Distr-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Wear-Distr-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-PutOn-Distr-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Zap-Distr-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Read-Distr-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-ClosedDoor-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-LockedDoor-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-LockedDoor-Fixed-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-WoD-Easy-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-WoD-Medium-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-WoD-Hard-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-WoD-Pro-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Levitate-Boots-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Levitate-Ring-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Levitate-Potion-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Levitate-Random-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Levitate-Boots-Fixed-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Levitate-Ring-Fixed-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Levitate-Potion-Fixed-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Freeze-Wand-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Freeze-Horn-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Freeze-Random-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Freeze-Lava-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-LavaCross-Levitate-Potion-Pickup-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-LavaCross-Levitate-Potion-Inv-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-LavaCross-Levitate-Ring-Pickup-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-LavaCross-Levitate-Ring-Inv-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-LavaCross-Levitate-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-LavaCross-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Quest-Easy-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Quest-Medium-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}
Couldn't instantiate MiniHack-Quest-Hard-v0. Reason: NLE environment missing required obsv key(s): {'tty_cursor', 'tty_chars'}

Packages versions:
gym                  0.23.0
gym-minigrid         1.1.0
minihack             0.1.4
nle                  0.9.0
nle-language-wrapper 0.2.0 

Any guidance or suggestions would be greatly appreciated – thank you!

**Comment by ngoodger** [comment]
Hey @saharad1 , I think I see the problem.  You need to tell Minihack which observation_keys you want it to provide.
That's how it's done in the [play script ](https://github.com/ngoodger/nle-language-wrapper/blob/main/nle_language_wrapper/scripts/play.py)

For example
```
env = NLELanguageWrapper(
        gym.make(
           "MiniHack-Room-Random-5x5-v0",
            observation_keys=[
                "glyphs",
                "blstats",
                "tty_chars",
                "inv_letters",
                "inv_strs",
                "tty_cursor",
                "tty_colors",
            ],
        )
    )
```

**Comment by saharad1** [comment]
Thanks for your help! it worked.
